### PR TITLE
Implement full drag control

### PR DESCRIPTION
**Pull request by reececomo**

### CODE REVIEW

**Comment by HarshilShah** [comment]
Hey there, thank you for this PR.

I like some of the changes here, and recognise that it plugs some important gaps in the library, however I have some different ideas about how this could be implemented (including some designs which circumvent the issues you are hacking around here) so I’m gonna hold off on merging this for now. I’ll be posting the RFC about the new design soon, and I’ll post a link here. I’d love your input on that design as well

**Comment by iDevelopper** [comment]
@reececomo , for what kind of application do you need that?

**Comment by reececomo** [comment]
@iDevelopper for a Utility app. It’s a great repo!

It does feels nice in your hand as a user to pull it up and down exactly under your thumb too.

Also been looking at SwiftEntryKit, can do a similar thing but also have an intermittent state at about half mast

**Comment by iDevelopper** [comment]
You can have a look at https://github.com/iDevelopper/PBPopupController, ideal for music app but can be used for any app.

**Comment by reececomo** [comment]
@iDevelopper I like the look of PBPopupController. I saw in your README it’s inspired by https://github.com/LeoNatan/LNPopupController - what are the differences between the two?

**Comment by iDevelopper** [comment]
@reececomo , the look and feel like apple music app since iOS 10 (for example deck presentation, animated image from popup bar, etc...)

**Comment by reececomo** [comment]
@iDevelopper oh cool, I’ll check it out! Thanks for the share

**Comment by iDevelopper** [comment]
@reececomo, ok if you want to discuss about it, I think it would be better to open an issue on  https://github.com/iDevelopper/PBPopupController

**Comment by HarshilShah** [comment]
Keeping with iOS 13’s updated design, some parts of this PR will be implemented in an upcoming release. You can read more about it here: #109. I’m closing this PR for now.

**Comment by reececomo** [comment]
Thanks @harshilshah

**Pull request closed without merging**
