### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheAbstractDev**

### CODE REVIEW

**Comment by HarshilShah** [comment]
Closing this because the existing documentation is correct and works as expected.

If you have a problem with a particular bit of code in the library, please open an issue or PR about it; working around a problem you haven't even described by just modifying the ReadMe is poor form.

**Comment by TheAbstractDev** [comment]
Where is the DeckSegue file ?
It's not working on the storyboard !

**Comment by HarshilShah** [comment]
I'm not sure where you're going wrong. I just started a blank new project, added just the `DeckTransition` pod, and it's working fine here. You can see for yourself here: [DeckTest.zip](https://github.com/HarshilShah/DeckTransition/files/1879465/DeckTest.zip)

Here are the segue's properties:

screen shot 2018-04-05 at 3 21 52 pm

You don't even need to set those manually; Xcode shows you a menu when you create a Segue, and you can just select `custom` and then `deck` from there:

screen shot 2018-04-05 at 3 22 29 pm
screen shot 2018-04-05 at 3 22 34 pm

**Comment by TheAbstractDev** [comment]
I see that it's working for you.
I use it with Carthage and it's not working, I had to create a custom UIStoryboardSegue to get it working.

**Comment by HarshilShah** [comment]
It's working in Carthage as well. Feel free to file a separate issue or PR once you figure out what your problem is.

**Pull request closed without merging**
